### ISSUE TITLE
Implement JSX syntax

### ISSUE THREAD

**Issue by nzakas** [eslint/typescript-eslint-parser#18]
Phase 2 is to add JSX syntax support into this parser. This would involve:

1. Converting the TypeScript JSX syntax tree into an ESTree-compatible one.
1. Convert the TypeScript tokens into Esprima-style tokens.
1. Making the result pass the JSX tests that are already tests in tests/fixtures/ecma-features/jsx.

@JamesHenry are you interested in taking a stab at this?

**Comment by JamesHenry** [comment]
Thanks a lot for mapping out those steps, yes I'll try and find some time this weekend!

**Comment by JamesHenry** [comment]
I have made some progress on this, but I have some questions on how to approach some of the conversions. What is the best way for us to chat about that? Gitter?

**Comment by JamesHenry** [comment]
There seem to be some fundamental issues in our more "interesting" jsx test at the moment, and I have reported the first one here: https://github.com/Microsoft/TypeScript/issues/7410

**Comment by nzakas** [comment]
If I'm on gitter, yes, though I'd prefer such issues be documented here so we have a good record.

**Comment by JamesHenry** [comment]
Great point - if I have concrete questions I will post them here. I am going to stop now as this has ended up dominating my weekend, but I have made a lot of progress (as much as anything in my personal understanding of eslint internals, ASTs and tsc output :) ).

The current status is:
- 3 tests are unrunnable due to the issues reported to TS above
- 3 remaining non-passing tests

I'll keep you updated on my progress as and when I find time during my evenings next week!

**Comment by nzakas** [comment]
Awesome, thanks so much!

**Comment by nzakas** [comment]
If you manage to get the three failing tests working, I'd say just remove the tests that fail due to the TS issues and we can handle those as bugs.

**Comment by JamesHenry** [comment]
Just noting down this third TS issue here for reference: https://github.com/Microsoft/TypeScript/issues/7471
