### ISSUE TITLE
Parsing error: node.attributes.map is not a function

### ISSUE THREAD

**Issue by madhavajay** [eslint/typescript-eslint-parser#275]
**What version of TypeScript are you using?**
"typescript": "2.3.2"

**What version of `typescript-eslint-parser` are you using?**
"typescript-eslint-parser": "^2.1.0"

**What code were you trying to parse?**

```
import * as React from 'react';
import { render } from 'react-dom';

const root = document.getElementById('root');

render(<div></div>, root);

```

**What did you expect to happen?**
Linting output

**What happened?**
0:0  error  Parsing error: node.attributes.map is not a function

.eslintrc.js made from eslint --init and choosing airbnb and react
```
module.exports = {
    "extends": "airbnb",
    "parser": "typescript-eslint-parser",
    "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ]
};
```

Trying to understand what this error is about and how to fix it. Any help would be greatly appreciated.

**Comment by soda0289** [comment]
Thanks for the report.

This fixed in the master branch and will be part of the next release which should be out sometime in the next couple of days. Typescript 2.3 changed the way that JSX nodes were parsed. To fix this you can either downgrade to TypeScript 2.2 or use the master branch of this parser.

**Comment by JamesHenry** [comment]
v3 was released on npm
