### ISSUE TITLE
Question: ts-eslint-parser & babel

### ISSUE THREAD

**Issue by 43081j** [eslint/typescript-eslint-parser#460]
A question rather than an issue.

While looking through #441 and babel's referenced issue, it seems like anyone who tries to PR that issue will end up writing near enough the same code as what babel-eslint pushed to solve the same problem a while ago.

Will there be a point where this and babel-eslint are aligned and achieve the exact same result? With babel/babel-eslint#505 solved (because babel already supports typescript), will the two projects do the same thing?

It is good to have choice, so i'm not asking if one will make the other obsolete. Rather just wondering if they will always be aligned and interchangeable.

**Comment by JamesHenry** [comment]
Thanks for the question, @43081j!

There will definitely be continued convergence, but it may be that the parsing done in this project needs to live on, even with babel supporting TypeScript.

This is because this project leverages the TypeScript compiler directly, and therefore has immediate access to the latest features of the language.

I can't give any exact predictions right now, but I'm in regular contact with the TypeScript team so rest assured there won't be any wasted efforts! 😄
