### ISSUE TITLE
20.1.0 release contains a breaking change

### ISSUE THREAD

**Issue by alexzherdev** [eslint/typescript-eslint-parser#534]
**What version of TypeScript are you using?**
3.1.3

**What version of `typescript-eslint-parser` are you using?**
20.1.0

**What did you expect to happen?**
When upgrading from 20.0.0 to 20.1.0 there are no breaking changes.

**What happened?**
As discussed in https://github.com/yannickcr/eslint-plugin-react/pull/2032, changing a dep to peerDep in #526 is a breaking change.

**Comment by platinumazure** [comment]
My apologies, I mislabeled the commit as a chore rather than breaking.

I'll revert the commit, cut a patch release, then redo the commit as breaking and cut a major release. I'm traveling today, so I greatly appreciate your patience as I find time to do this in between airline security, etc. Thanks for your understanding!

**Comment by platinumazure** [comment]
I think I've published typescript-eslint-parser@20.1.1 reverting the peer dependency change. (I say "I think" because this is the first time I've used our new release pipeline with npm 2FA. I do see commits on GitHub and an artifact on npm, so hopefully all went well.)

I'm about to fly now, so I'll do the second part (apply the commit as breaking and cut major release) later today.
