### ISSUE TITLE
Parsing error on `new` operator without parentheses

### ISSUE THREAD

**Issue by daluege** [eslint/typescript-eslint-parser#60]
Whenever a TypeScript contains a `new` operator without parentheses, the following error is thrown by `eslint`:

    Parsing error: Cannot read property 'map' of undefined

According to the [TypeScript spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.14), however, this syntax is valid.

Context:

    eslint@3.3.1
    typescript-eslint-parser@0.1.2

.eslintrc.yml:

    extends: eslint:recommended
    parser: typescript-eslint-parser

test.ts:

    function X () { }
    new X;

**Comment by nzakas** [comment]
What version of TypeScript are you using?

Can you paste in the complete output that you're seeing?

**Comment by JamesHenry** [comment]
@nzakas I can reproduce this.

It turns out TypeScript just leaves off the `arguments` property from its NewExpression node when you don't provide the parens. We are trying to map over them without checking if the property exists.

Fix coming up!

**With Parens:**
![unspecified-9](https://cloud.githubusercontent.com/assets/900523/17866394/43433e06-689e-11e6-8a35-6f98a774fb2e.png)

**Without Parens:**
![unspecified-10](https://cloud.githubusercontent.com/assets/900523/17866399/464f26be-689e-11e6-8f2d-dfc80ee610e7.png)

**Comment by JamesHenry** [comment]
PR here https://github.com/eslint/typescript-eslint-parser/pull/62

**Comment by nzakas** [comment]
Awesome work, thanks.
